name: server ci
on:
  push:
    branches:
    - dev
    - release/*
  pull_request:
    branches:
    - dev

jobs:
  build:
    name: server build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - run: |
          go version
          make
